### ISSUE TITLE
Linker error in OSX

### ISSUE THREAD

**Issue by ys1382** [cossacklabs/themis#205]
ld: warning: directory not found for option '-L/<project dir>/Pods/OpenSSL-Universal/lib-ios'

I see I have the directory lib-macos, but it seems to be looking for the iOS one.

To reproduce: add themis pod to Podfile, compile project.

Using OSX Sierra, Xcode 8.3.2

**Comment by vixentael** [comment]
Thank you @ys1382 

I think i found a problem in podspec
https://github.com/cossacklabs/themis/blob/master/themis.podspec#L16

I'll fix it soon

**Comment by vixentael** [comment]
hi @ys1382 

i've updated podspec, linking to correct path for Open SSL for MacOS.

Commit https://github.com/cossacklabs/themis/commit/156ca9af94a7210c0d116717c4685f24e155cf29


Raw podspec
https://gist.githubusercontent.com/vixentael/4fb81d87c5627fbef2004e8a496454ec/raw/9e9d4a64dbf322934a5e9619b59f0f5995f2392e/themis_fix.podspec

I can confirm that newly created MacOS project in xcode is building success with this podspec. Can you please take a look if it works for you?

**Comment by ys1382** [comment]
I still get the error on OSX: ld: warning: directory not found for option '-L/<dir>/gochat/apple/osx/Pods/OpenSSL-Universal/lib-ios'

You can try it for yourself here: https://github.com/ys1382/gochat/tree/themis/apple/osx

**Comment by vixentael** [comment]
That's true, because I haven't pushed new Themis pod without your confirmation :) 

To check that everything is working, please link pod to the updated podspec directly. Link this
https://github.com/ys1382/gochat/pull/5

After your confirmation, I'll merge this podspec into master. It will be updated in CocoaPods repo when Themis 0.9.5 will be released. Until then, please link to the podspec directly.

Thank you

**Comment by ys1382** [comment]
Fixed
