### ISSUE TITLE
Can't build via CocoaPods on macOS High Sierra

### ISSUE THREAD

**Issue by sgammon** [cossacklabs/themis#219]
hey there,

i found your pod and it looks really great, i'd love to use it but cocoapods reports:
```
[...]
Installing themis (0.9.4)
[!] The 'Pods-Phone-Bloom' target has transitive dependencies that include static binaries: (/Volumes/PROPHET/Vault/Code/bloom-ios-prototype/Pods/OpenSSL-Universal/lib-ios/libcrypto.a and /Volumes/PROPHET/Vault/Code/bloom-ios-prototype/Pods/OpenSSL-Universal/lib-ios/libssl.a)
```

i would be happy to help submit a PR or help test if someone can point me in the right direction
i've tried with `themis` `0.9.4`, and with `master`

**Comment by vixentael** [comment]
Hi @sgammon!

Thank you for pointing this out!

#### Challenge we face

Themis depends on the [OpenSSL](https://github.com/krzyzanowskim/OpenSSL) pod, that is shipped as static library. As you know, it's quite difficult to use both static libraries and frameworks in your Podfile since CocoaPods 1.0.0 (large discussions were happen here: https://github.com/CocoaPods/CocoaPods/issues/2926,  https://github.com/CocoaPods/CocoaPods/issues/3583 and https://github.com/CocoaPods/CocoaPods/issues/3729)

Also there's an open issue in OpenSSL repo https://github.com/krzyzanowskim/OpenSSL/issues/9 according switching to frameworks.


#### Our plan

One of the best options for Themis would be using OpenSSL as dynamic framework, that is discussed here #128. However, building and supporting dynamic frameworks for static libs is quite messy. Maybe one day we will switch to BoringSSL instead, as grpc maintainers did when they came across the same problem (https://github.com/grpc/grpc/issues/4121).


#### Workaround to make it work now

As workaround I can suggest you to add these lines to your Podfile:

```
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```

Please let me know if it helped!

**Comment by sgammon** [comment]
i'm sorry but i've tried the fix you mention and it no longer seems to work. i get the same error. if it helps, i'm on cocoapods `1.3.1`

i do understand the conundrum, but this is of course a show stopper bug for people already using dynamic frameworks in their code. i really like themis and the ecosystem of other software around it but i'm afraid this prevents us from being able to consider it for adoption at all.

BoringSSL would make me very happy as a user both because it is solid software and because it would fix this issue.

i'm familiar with it and i understand that it largely replaces similar interfaces exposed by OpenSSL, but i've also heard that code is rather nuanced.

is there a plan to actually implement BoringSSL, or is it really a "maybe someday" kind of thing?

as i mentioned earlier, i would be glad to help if my skillset has any value for solving this problem

**Comment by gene-eu** [comment]
We're migrated some other versions of Themis to BoringSSL already (I'm pretty sure about Android, and I recon hearing we wanted to do so for Linux as well at some point), so this is  rather a question of replicating that experience on iOS, shouldn't bee too complex. 

Thank you for your generous offer, I think we'll

**Comment by gene-eu** [comment]
We're migrated some other versions of Themis to BoringSSL already (I'm pretty sure about Android, and I recon hearing we wanted to do so for Linux as well at some point), so this is  rather a question of replicating that experience on iOS, shouldn't bee too complex.

**Comment by vixentael** [comment]
I found this

https://github.com/levigroker/GRKOpenSSLFramework

This is pod with dynamic frameworks based on https://github.com/krzyzanowskim/OpenSSL repo and discussions I mentioned earlier. I'll try to link podspec to this dependency instead.

Give me some time, I'll be back.

**Comment by vixentael** [comment]
Hi @sgammon 

I've updated podspec to use GRKOpenSSLFramework as dependency in [separate branch](https://github.com/cossacklabs/themis/tree/podspec_dynamic_frameworks_GRKOpenSSLFramework). You shouldn't have 'transitive dependencies' error right now.

Can you please update your podfile and link to the podspec directly, like this:

```ruby
  pod 'themis', :podspec => 'https://raw.githubusercontent.com/cossacklabs/themis/podspec_dynamic_frameworks_GRKOpenSSLFramework/themis.podspec'
```

One thing I don't really like is that I disabled CLANG modules to make project built. This feels wrong and prevents running pod spec lint successfully (more discussion --> #128).

Please let me know if this themis spec works for you :)

**Comment by vixentael** [comment]
@sgammon 

I know how to switch to OpenSSL dynamic frameworks without a "CLANG modules mess" 😄 
I described our next steps here --> https://github.com/cossacklabs/themis/issues/128#issuecomment-326080182

I'll keep you updated when merge that changes into release branch.

**Comment by sgammon** [comment]
I will try it with these changes tonight and report back. it would still be the preferred route IMO though to build off of boringSSL which has a shorter patch cycle than openSSL, although i will take what i can get ;)

**Comment by sgammon** [comment]
```
ld: '/Volumes/PROPHET/Vault/Code/bloom-ios-prototype/Pods/GRKOpenSSLFramework/OpenSSL-iOS/bin/openssl.framework/openssl' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Volumes/PROPHET/Vault/Code/bloom-ios-prototype/Pods/GRKOpenSSLFramework/OpenSSL-iOS/bin/openssl.framework/openssl' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

😞

**Comment by sgammon** [comment]
Perhaps we could fork that and re-build w/bitcode?

**Comment by vixentael** [comment]
Currently i've update podspec to disable bitcode :)
https://github.com/cossacklabs/themis/blob/release_0.9.5/themis.podspec


Will google tomorrow what are the best options to re-build frameworks

**Comment by sgammon** [comment]
Ok, disabling bitcode (temporarily) in my project and all pods has it building with the modified Podspec for themis.

**Comment by vixentael** [comment]
I've opened PR in GRKOpenSSLFramework repo
https://github.com/levigroker/GRKOpenSSLFramework/pull/3

I think we'll have bitcode support quite soon :)

**Comment by sgammon** [comment]
thanks @vixentael. looking forward to it! right on.

**Comment by sgammon** [comment]
hey @vixentael - one small issue. i get this warning when building with `themis` now. i'm sure you'll fix it before release, just wanted to make sure you were aware :)

let me know if I can help in any way. thank you again!

<img width="649" alt="screen shot 2017-09-02 at 10 16 45 am" src="https://user-images.githubusercontent.com/171897/29997440-f6414f06-8fc7-11e7-8f9e-628407944184.png">

**Comment by vixentael** [comment]
Thank you @sgammon 

Unfortunately this happens because it's unreal to preserve the folder structure using CocoaPods. Themis core has two different files with the same name `error.h` files inside different folders: `themis` and `soter`. After integrating Pod, the folder structure is 'flat' and both files are situated on the same level of depth (that's why Xcode complains).

The only way to preserve folder structure is to create subspec inside podspec, however it's not an option for us: soter is not a separate part of the project and shouldn't be moved into separate subspec.

If you believe that this warning is crucial, please **open a separate Issue**, we'll try to use magic renaming technique: rename `error.h` inside themis-core! 

However I can't promise that it's a quick solution: need to make sure that all wrappers are not affected :)

**Comment by vixentael** [comment]
Dear @sgammon 

After long days of fixing-updating-trying-repeating-again, I can say that branch https://github.com/cossacklabs/themis/tree/release_0.9.5 contains Themis podspec that fully supports bitcode.

Please link Themis to your project as
`pod 'themis', :git => "https://github.com/cossacklabs/themis.git", :branch => 'release_0.9.5'`

Consider this as pre-release version :)

We will publish release very soon (need to update other wrappers as well).

Please re-open this issue if you still experience difficulties.

Thank you a lot for your help and patience!

**Comment by sgammon** [comment]
Thank you @vixentael!! Very excited to get started with themis

**Comment by vixentael** [comment]
@sgammon Themis 0.9.5 is officially out! 

Now you can write in your podfile `pod 'themis', '0.9.5'` 💪
