### ISSUE TITLE
Support install via `brew install` 

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#274]
As we [discussed previously](https://github.com/cossacklabs/themis/issues/101), this would be very useful for macOS users.

**Comment by ilammy** [comment]
I've decided to give it a shot and hacked this:

https://github.com/ilammy/homebrew-themis

And Ruby turned out to be not that hard 😌

The formulas are not ideal but that's at least something to start with. They hardcode the current stable version of Themis: 0.10. It works for me and for Travis, and will hopefully work for somebody else. Please test.

Themis requires _some_ crypto backend and Homebrew insists on using Homebrew-installed WhateverSSL for other Homebrew-installed packages. It seems that only OpenSSL and LibreSSL are available via Homebrew by default, so I've added (mutually excluding) formulas for both. The users will have to make the choice explicitly, but developers should be smart enough for that.

Here's also a funny side note. Homebrew's documentation suggests writing some tests to verify the installation. So I did, adding a test which builds a simple C program using `themis_version()` to verify that we have installed the correct version of Themis. And it turned out that there's a minor bug in this function: it insists that Themis' version is 0.9 when in fact it should be 0.10. (Here are the culprits: [themis.h](https://github.com/cossacklabs/themis/blob/master/src/themis/themis.h#L33), [soter.h](https://github.com/cossacklabs/themis/blob/cb4b7341a5b8c1e59aec8cff87dd134116063401/src/soter/soter.h#L33).)

**Comment by vixentael** [comment]
Thank you, @ilammy! You're right, formulas look quite easy. Give us some time to take a deep look.

I think it would be useful to merge homebrew formulas into the main repo.

I've created #324 separately to update hardcoded versions.

**Comment by ilammy** [comment]
@vixentael

> I think it would be useful to merge homebrew formulas into the main repo.

I agree. It's better to have the formulas in the same _cossacklabs_ namespace as the library itself.

I've looked through some repos on GitHub and it seems to be much more common to keep Homebrew formulas in a separate repository from the main project source code. This is due to the fact that Homebrew clones the repo with formulas when it's added to the system. In this case the formula repository needs to be updated only when a new version of the software is released, not every time something is pushed to the master branch (and consumes way less disk space).

Thus I believe the formulas should be placed into some new repository like _cossacklabs/homebrew-themis_ rather than directly into this one. Other projects like Arca (which uses Themis) may also benefit from Homebrew packaging, so you may want to have a single repository for all Cossack Labs projects in one place for the ease of maintenance.

**Comment by vixentael** [comment]
Hooraay, it's happened!

https://github.com/cossacklabs/homebrew-tap/

Docs and readme to be updated
