### ISSUE TITLE
Can I use secp256k1 keys and/or ECDH secret to encrypt using themis?

### ISSUE THREAD

**Issue by FrankC01** [cossacklabs/themis#322]
Now that we have themis running: We've been generating keys and DH secrets from same using secp256k1. Is it possible to use either for themis encrypt/decrypt?

**Comment by vixentael** [comment]
Themis [Secure Message](https://github.com/cossacklabs/themis/wiki/Secure-Message-cryptosystem) is designed for encrypting/decrypting data between two peers – the encryption key will be derived by ECDH. Take a look on [Python example](https://github.com/cossacklabs/themis/wiki/Python-Howto#secure-message).

Currently, Themis is using another curve: `secp256r1` aka `ANSI X9.62 prime 256v1` aka `NIST P-256`. However, we designed Themis to make it possible to change the source of crypto-primitives rather easy by patching [Soter crypto core](https://github.com/cossacklabs/themis/wiki/Soter). 

All you need to do it [to support another curve](https://github.com/cossacklabs/themis/search?utf8=%E2%9C%93&q=SOTER_ASYM_KA_EC_P256&type=) and to update corresponded tests. We would appreciate pull request and mention your team as significant contributors for this change!

If you feel time or skills pressure, we can help you with this patch – just drop us an email to [dev@cossacklabs.com](mailto:dev@cossacklabs.com).

**Comment by FrankC01** [comment]
@vixentael OK, I will check through the references, I will check out the source points and tests and will look at time available... no problem and happy to contribute vis-a-vis pull request

**Comment by branaway** [comment]
any update on this issue, guys? I'd like to reuse the key pair from my Ethereum account for secure messaging. I need the support of secp256k1 for the purpose.

**Comment by vixentael** [comment]
hi @branaway thank you for your interest! 

Currently we are focused on improving Themis API and distribution ways on multiple platforms (f.e. we've added fully compatible RustThemis in [the latest 0.11.0 release](https://github.com/cossacklabs/themis/releases/tag/0.11.0)).

Adding support of `secp256k1` is not on the top of our priority list for now (however, if you are building commercial project and timeline is crucial for you, you should consider the pro's of [commercial support for Themis](https://github.com/cossacklabs/themis#commercial-support)).

However, adding `secp256k1` is not a rocket-science, we did a deeper look, and these are the detailed description of steps needed:

#### Extend Soter with new curve type

First of all, let Soter know that there will be a new curve. Themis uses Soter as connector between various crypto-engines (see [detailed description](https://github.com/cossacklabs/themis/wiki/Soter)). 

1. Add new type of EC curve to the list of supported types:
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/soter_asym_ka.h#L35

2. If key length is different from key length supported by Themis, then add new lengths to the list:
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/soter_ec_key.h#L31

#### Call `secp256k1` implementation from Soter

Both [BoringSSL](https://github.com/google/boringssl/blob/master/include/openssl/nid.h#L3163) and [OpenSSL](https://wiki.openssl.org/index.php/Command_Line_Elliptic_Curve_Operations) claim to support `secp256k1`. So second phase is to call their implementation from Soter.

(next steps are described for Soter-OpenSSL, and similar steps are needed to extend Soter-BoringSSL).

1. Register support of `secp256k1` for OpenSSL, link Soter name of the curve with corresponded [curve name](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/ssl/t1_lib.c#L160) from OpenSSL
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_asym_ka.c#L27

2. Tell Soter-OpenSSL that new curve is supported:
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L27

3. Handle key lengths:
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L37
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L51
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L65
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L79

4. Expand Soter to use keys in OpenSSL format for new curve
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L270
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/soter/openssl/soter_ec_key.c#L367

#### Propagate changes to Themis

Teach Themis to use new curve type, and respectively, update required language wrappers for new curve type. As soon as Themis can't use both curves at the same moment, we shall parametrize it and allow users to redefine curve type.

1. Update code to use different curve type instead of hardcoded one:
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/themis/secure_message_wrapper.c#L379

2. Add `SECURE_MESSAGE_EC_CURVE` parameter to switch between curves, and setup it as `SOTER_ASYM_KA_EC_P256` by default
https://github.com/cossacklabs/themis/blob/release/0.11.0/src/themis/secure_message_wrapper.h

3. Create new init method that will allow Themis to use new curve in runtime. Currently Themis uses only one curve, so we haven't think how to switch between curves.

#### Infrastructure

1. Tests-tests-tests-tests-tests.

2. Copy-paste changes for Soter-BoringSSL backend (or handle case when users will use ThemisBoringSSL with unsupported curve).

**Comment by vixentael** [comment]
One more note: `secp256k1` changes should be carefully propagated into Themis libraries that are distributed. 

I don't know your use-case, but I can imagine a situation, when server-side developer starts using Themis with `secp256k1`, while client-side developer (let's say iOS) will download Themis from CocoaPods that is using `secp256r1`. Compatibility issues.

Our goal not to make yet-another-openssl, but to provide easy-to-use and hard-to-misuse library that is fully compatible across 11 languages (three server-side platforms, two mobile-side platforms, containers, various process architectures yadda yadda), so adding new curve is smth to be carefully handled for each use-case.
