### ISSUE TITLE
Update or remove hardcoded versions inside code

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#324]
`themis_version()` is used to verify that we have installed the correct version of Themis. 

However, versions are not updated to `0.10.0`
https://github.com/cossacklabs/themis/blob/master/src/soter/soter.h#L33
https://github.com/cossacklabs/themis/blob/master/src/themis/themis.h#L33

Thank you @ilammy for finding this

**Comment by ilammy** [comment]
Hm... After giving it some thought I believe that `themis_version()` function by itself has little practical value and can be removed. However, it may be useful to have the version available somewhere.

This function returns a human-readable string which is not really expected to be consumed by programs. Sure, it may be useful for printing out some banner at application startup, but if one wants to check Themis version at run-time they would rather have a more convenient API like this one:

```c
int themis_version_major(void);
int themis_version_minor(void);
int themis_version_patch(void);
```
Integers are immediately usable, you don't need to parse them.

Though, I kinda struggle to come up with a legitimate use-case for checking Themis version at run-time. It's far more likely to have a need for compile-time checks instead. For example, having some preprocessor defines enables writing code that compiles with different versions of Themis:

```c
#if THEMIS_VERSION_CODE < THEMIS_VERSION(0,10,0)
    themis_legacy_api();
#else
    themis_modern_api();
#endif
```

Versions are also important for API/ABI compatibility when dynamically-linked libraries are involved. Shared objects should include the version field so that dynamic linker may load an appropriate library and refuse to load incompatible ones. Incidentally, Themis currently does _not_ include a version field in its shared libraries (soname), so it is possible to accidentally break applications by making incompatible changes in API or ABI. (I guess this is worth creating another issue...)

I personally use `themis_version()` mostly as a sanity test. It is redundant to download the source code for Themis v0.10, build it, and then check that you have indeed built Themis v0.10. It's a nice safety check, but not a critical one.
