### ISSUE TITLE
Fix CircleCI/Bitrise build of Android integration tests

### ISSUE THREAD

**Issue by vixentael** [cossacklabs/themis#350]
Looks like the integration tests for Android Themis wrapper are failing in CircleCI again.

It's not a change in a Android Themis wrapper, I believe it's connected with Android ecosystem changes (modules/ABI/API etc).

https://circleci.com/gh/cossacklabs/themis/1504

```
:boringssl:generateJsonModelDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':boringssl:generateJsonModelDebug'.
> Error occurred while communicating with CMake server. Check log /home/user/project/third_party/boringssl/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_server_log.txt for additional information.
```

Any Android dev gurus out here? :)

**Comment by ilammy** [comment]
To make things even more complicated, recent builds of the same branch fail for a different reason:

https://circleci.com/gh/cossacklabs/themis/1510

Now this is something related to licenses. It seems that Android SDK license was updated on 2019-01-16. It requires manual acceptance of the license via the SDK manager.

I tried installing the latest package inside the Docker container via

    sdkmanager "cmake;3.10.2.4988404"

This fixed the licensing error. Now I see the expected communication error instead 😁

I have no idea, actually, how Gradle works, but I suspect that the CMake version is to blame. There are some warnings in the build output about CMake 3.7+ being experimental and unsupported. Android SDK seems to have CMake 3.6 available, and maybe we should stick to that.

[BoringSSL submodule has been updated recently,](https://github.com/cossacklabs/themis/commit/486e565161930225fab56c1e46530e5504dcebd6) I guess I'll try looking into changes to dependencies. Maybe they have changed the requirements from "3.6 only" to "whatever" or something...

**Comment by ilammy** [comment]
Okay... The submodule update has nothing to do with that, sorry for misdirection.

It seems that Gradle just pulls in the latest CMake package version during the build (3.10). I have tried installing CMake 3.6 specifically via `sdkmanager` and that did the trick. I was able to manually build Themis and run the tests in a container (they passed, yay!) Maybe Google added CMake 3.10 recently and this has messed up our build which relied in "latest CMake" being suitable for BoringSSL.

I tried to pin CMake's version in `build.gradle` [as told by the docs](https://developer.android.com/studio/projects/add-native-code#vanilla_cmake), but that did not work for me with a clean build. Gradle still demanded an accepted license for CMake 3.10.

Well... It seems that in order to fix this issue the Docker image has to be rebuilt (or updated) to include the accepted new license. And maybe include `'cmake;3.6.4111459'` specifically, just in case.

(Also, I have to say that Android CI build is _veeeeeeery slooooooow_. Maybe that has something to do with the fact that it builds BoringSSL (with tests) for all CPU architectures supported by Android. But anyway! Twenty minutes is a tad too much, I think. Maybe we could cut some corners...)

**Comment by vixentael** [comment]
> It seems that in order to fix this issue the Docker image has to be rebuilt (or updated) to include the accepted new license. And maybe include 'cmake;3.6.4111459' specifically, just in case.

what kind of Docker image do you mean?

**Comment by ilammy** [comment]
I'm talking about the `cossacklabs/android-build` image which is the one used by CircleCI.

However, I've tried building it myself from the [Dockerfile](https://github.com/cossacklabs/dockerfiles) and it did not work either. At least, right out of the box. First there were some issues with latest licenses (those got solved, I think), then I've encountered an issue with older Gradle missing the MIPS toolchain (worked around it), and currently I'm back to square one with the build producing the same Cmake server communication error.

It seems that simply rebuilding the image will not fix the issue (and it might be unnecessary at all).

**Comment by ilammy** [comment]
I have managed to build an updated image, then build Android Themis and successfully run the tests like the CI would do.

This required the following changes:

- [in Dockerfile](https://github.com/cossacklabs/dockerfiles/compare/cossacklabs:e9c4552...ilammy:e2363a4) for `cossacklabs/android-build`
- [in build system](https://github.com/cossacklabs/themis/compare/cossacklabs:d2e5f25...ilammy:d66ae58) for BoringSSL and Android Themis

I'm not really sure in them, especially how they will affect the production usage of Themis on Android. For example, I don't know about the issues that using clang instead of gcc may bring. It might also be necessary to update the documentation to ensure that CMake 3.6 is used for building Themis. It might be a good idea to upgrade to a newer Gradle version instead of those workarounds that I used.

I have one physical Android device and I'll check Themis there later, but that's as much testing as I can perform personally. I would like a second opinion on the changes before submitting any pull requests. Please review.

**Comment by vixentael** [comment]
got it, will take a deeep _(and very slooow as android devices' usual speed)_ look

**Comment by vixentael** [comment]
@ilammy Currently all these changes seems valid and important (still testing though).

A bit of reasoning (for future us).

1. Downgrading cmake version to 3.6 due to incompatibility BoringSSL with cmake > 3.7 and license issues.

2. Change default compiler to build BoringSSL to Clang due to their giving up the GCC. 

```
  CMake Error at /home/user/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake:169 (message):
   GCC is no longer supported.  See
   https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md.
```

3. Update gradle to build BoringSSL.

**Comment by vixentael** [comment]
Android Themis BoringSSL dockerimage was tested in [Themis Java examples](https://github.com/cossacklabs/themis-java-examples/pull/1): all good.

**Comment by vixentael** [comment]
@ilammy my bad, I haven't tested with Themis BoringSSL for desktop, thus latest Android tests are successful, but desktop tests are failing (https://circleci.com/gh/cossacklabs/themis/1539).

```
link soter_static                   [OK]
building embedded BoringSSL...
/bin/bash: cmake: command not found
src/soter/boringssl/soter.mk:39: recipe for target 'build_with_boringssl/boringssl/crypto/libcrypto.a' failed
```

Thus, I moved back cmake installation in container
https://github.com/cossacklabs/dockerfiles/pull/2

**Comment by ilammy** [comment]
@vixentael, r-r-right. I tested only Android as well, and forgot that the same container is used for other builds which need CMake too 😅

It seems that Gradle is smart enough to prefer its own CMake before the system one, so keeping it should be fine.

**Comment by vixentael** [comment]
At the end, this issue was solved by linking exact cmake version to sdkmanager, updating gradle, switching BoringSSL compilation to clang instead of gcc.

PRs:
- update dockefile / docker image
https://github.com/cossacklabs/dockerfiles/pull/1
https://github.com/cossacklabs/dockerfiles/pull/2

- update BoringSSL build:
https://github.com/cossacklabs/themis/pull/352

**Comment by vixentael** [comment]
Solved by https://github.com/cossacklabs/themis/pull/352

Thank you @ilammy
