### ISSUE TITLE
Header not found when adding Themis as dependency in a new development cocoapod

### ISSUE THREAD

**Issue by popaaaandrei** [cossacklabs/themis#411]
### Issue description
I am adding Themis as a dependency in a new development cocoapod like this:
`s.dependency 'themis', '0.10.3'` (also tried with `s.dependency 'themis/themis-openssl', '0.10.3'`)

I have 2 errors when trying to build the project:
- `'soter/soter_error.h' file not found` inside `themis/themis_error.h` line 31 (#include <soter/soter_error.h>)
- and obviously `Could not build Objective-C module 'themis'` where I am importing themis

### Environment info

**OS:** iOS 10
**Cocoapods** 1.5.3
**Themis version:** 0.10.0/2/3

**Installation way:** via package manager
**Crypto provider:** OpenSSL I think

**Comment by vixentael** [comment]
Seems that this gonna be a long journey :)

1. There are existing pods that use Themis as dependency pod:

https://github.com/cossacklabs/acra/blob/master/acrawriter.podspec

But note two things:
  - this is a cocoapod made from **objc** code
  - it sets up `'HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/themis/src" "${PODS_ROOT}/themis/src/wrappers/themis/Obj-C"'` to fix header-searching issue.

So, first issue is fixed just to setting up correct HEADER_SEARCH_PATHS so Themis could find all its files.

2. However, if you do that, you will experience next problem. If you try to create **Swift** framework, Xcode will try to build **Swift module** from objective-c files. And this is the place where rabbit hole starts.

3. I've played a bit myself with our Swift example project in [vxtl/ios-header](https://github.com/cossacklabs/themis/compare/vxtl/ios-header) branch. Original example is written in Swift and uses **Bridging header** to import Themis file. Bridging header contains very simple `#import <objcthemis/objcthemis.h>` that imports all needed headers, and everything is working fine.

4. Unfortunately, when building Swift frameworks (or CocoaPod) that uses ObjC code, you can't use Bridging headers ([because Apple said so](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift)), but should use **modular frameworks** instead.

5. You can simulate this behavior taking above mentioned example project and write `import themis` inside Swift code. This makes Xcode to build Swift modular framework, and fail. 

First, you see typical Xcode error message like
<img width="636" alt="screen shot 2019-03-06 at 2 06 16 am" src="https://user-images.githubusercontent.com/2877920/53846918-72da8780-3fb7-11e9-85ad-258d00c7bb9c.png">

because of `include non-modular header inside framework` error:
<img width="508" alt="screen shot 2019-03-06 at 2 01 00 am" src="https://user-images.githubusercontent.com/2877920/53846935-82f26700-3fb7-11e9-982d-868962de46be.png">

People say, that it's a typical error, when private headers are exposed into `.h` files. For example, [AFNetworking solved similar issue](https://github.com/AFNetworking/AFNetworking/issues/2205) just by moving some headers into `.m` files.

In Themis we can't hide all headers (although this was the first thing I tried to do in objc wrapper, results can be found in [vxtl/ios-header branch](https://github.com/cossacklabs/themis/compare/vxtl/ios-header)), but internal structure of Themis (themis, soter, openssl) has exposed headers and it's rather complicated to change it.

6. iOS gurus suggest to build modular framework, exposing required headers in custom `module.modulemap` (I found good blogposts [about modular frameworks](http://nsomar.com/modular-framework-creating-and-using-them/), [challenges in building them](https://medium.com/allatoneplace/challenges-building-a-swift-framework-d882867c97f9), [more challenges](http://ilya.puchka.me/objective-c-headers-in-swift-framework-custom-build-configurations/) and [more advice](http://nsomar.com/project-and-private-headers-in-a-swift-and-objective-c-framework/) and [even more](http://nsomar.com/modular-framework-creating-and-using-them/)).

So now I'm trying to add all required headers to the modulemap.

Issue I face right now is how to support complex multi-level folder structure in modulemap, because it looks like only "flat" files are supported:

<img width="634" alt="screen shot 2019-03-06 at 2 03 42 am" src="https://user-images.githubusercontent.com/2877920/53848206-25144e00-3fbc-11e9-964b-af2e2e885957.png">

**Comment by vixentael** [comment]
> In Themis we can't hide all headers (although this was the first thing I tried to do in objc wrapper, results can be found in vxtl/ios-header branch)

it actually worked 😱 

See updated Themis iOS wrapper code in #415, see new temporary Themis.podspec 0.10.4 in #416.

Upon confirmation, successful testing and merging, I'll push podspec officially.

**Comment by popaaaandrei** [comment]
Confirm that works for me. Thank you!

**Comment by vixentael** [comment]
@popaaaandrei themis `0.10.4` is public now :)
