### ISSUE TITLE
Trouble installing on Heroku

### ISSUE THREAD

**Issue by dloughran295** [cossacklabs/themis#480]
I have:

- trouble encrypting in swift and then decrypting the encrypted message in python.

----------------------------------------

### Issue description

"/app/.heroku/python/bin/python: undefined symbol: themis_secure_cell_decrypt_seal" is the error I am getting from python. I am using the function exactly described in the python how to and the swift how to. I am using the same master key as well. 

### Environment info

**OS:** Mojave 10.14.5

**Themis version:** 0.11.1

**Installation way:**
 - home-brew for swift
 -  via package manager for python

**Crypto provider:** I don't know

**Comment by vixentael** [comment]
hi @dloughran295 

1. It looks like pythemis installation issue for me. Could you please double check that you've installed Themis Core library first, then Themis python wrapper on your Heroku instance?

Please follow steps described here:
https://github.com/cossacklabs/themis/wiki/Python-Howto#installing-stable-version-from-pip

If your Heroku instance is based on Ubuntu, then you'll need to install Themis core via `apt-get install` first.

2.  The easiest way to check if pythemis installation is okay is to run local function, like key generation:

```
➜ python3
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythemis
>>> from pythemis.skeygen import GenerateKeyPair, KEY_PAIR_TYPE

# or KEY_PAIR_TYPE.RSA for RSA
obj = GenerateKeyPair(KEY_PAIR_TYPE.EC)
private_key = obj.export_private_key()
public_key = obj.export_public_key()

>>> print(public_key)
b'UEC2\x00\x00\x00-j\x8b*\x06\x03>4:\xe0\x84\xfeT \x8c\x9d\x151\xa3\xb0\xb3i\xa9\xf8C}w\xaeX\x88\xdcw#\xac\x80m\xb1\xb4'

>>> 
```

**Comment by dloughran295** [comment]
hi @vixentael,
It appears that I have all of the right installations as I am getting the same lines being printed out as you.

**Comment by vixentael** [comment]
@dloughran295 do you get these lines on your mac or on heroku?

Could you please write step-by-step how you installed Themis on Heroku?

**Comment by dloughran295** [comment]
@vixentael,
 I am getting these lines on my mac. And the way I install pythemis was by first installing it to my computer via pip and then for heroku I put pythemis in the requirements text file for the heroku to be able to run pythemis. Is there something I should do other than that in order for heroku to run it.

**Comment by dloughran295** [comment]
@vixentael, 
This is the encryption using swift:
<img width="695" alt="Screen Shot 2019-06-17 at 11 04 06 AM" src="https://user-images.githubusercontent.com/51305693/59615059-e7ad7980-90ef-11e9-82ce-2945900f2da2.png">

and this is the decryption using python:
<img width="554" alt="Screen Shot 2019-06-17 at 11 04 31 AM" src="https://user-images.githubusercontent.com/51305693/59615085-f005b480-90ef-11e9-9ac2-0091c619ec3f.png">

**Comment by vixentael** [comment]
> then for heroku I put pythemis in the requirements text file for the heroku to be able to run pythemis

I think you missed a step described above – to install Themis Core library on Heroku.

Please follow steps from https://github.com/cossacklabs/themis/issues/480#issuecomment-501867156.

It looks like you have installed only pythemis on Heroku. pythemis is a python wrapper around Themis core library, it won't work alone.

I also think that everything should work on your mac, because you installed Themis core library via brew, then swift themis, then pythemis via pip. So you get the whole set.

**Comment by dloughran295** [comment]
Hi @vixentael,
    I have been trying to go through those steps, yet I keep getting errors about with the sudo, wget, and echo commands. I am typing each step into the heroku command line but it isn't working.

**Comment by Lagovas** [comment]
@dloughran295 , it's hard to help you without error messages and description of the environment where you do it. Heroku provides several ways of how you can deploy your app. They run your code on pre-configured OS images (https://devcenter.heroku.com/articles/stack) which may or may not have some packages. And Heroku may to not provide the ability to install something else than you already have (actually I don't know because didn't try). Also you can deploy your app as docker container where you can install all that you want. 
I suggest you try to deploy your app with docker where you will have all rights to install packages or copy your logs with error here and tell us about environment/deploying scripts which you use.

**Comment by dloughran295** [comment]
@vixentael @Lagovas 
I tried again going through the steps in this link: [#480 comment](https://github.com/cossacklabs/themis/issues/480#issuecomment-501867156)

I got through steps 1 and 2, but when I tried to create a new *.list file, I get:

`tee: cossacklabs.list: Read-only file system`

It appears that heroku does not want me to create a new file in the sources.list.d directory. Any thoughts on how I can get around this?

**Comment by Lagovas** [comment]
1. you can try to build C library from sources - https://github.com/cossacklabs/themis/wiki/Building-and-Installing. after that place somewhere *.so files and then you should set LD_LIBRARY_PATH env variable in your code like 
```
import os
os.environ.setdefault('LD_LIBRARY_PATH', '/path/to/libraries')
# only after setup LD_LIBRARY_PATH import pythemis
from pythemis import smessage
```
where your own /path/to/libraries folder must contain libthemis.so and libsoter.so. Because heroku will not allow placing these libraries to system paths where OS search shared libraries by default. 
You can try to build these libraries in heroku env if it will have all needed dependencies (openssl, build-essential) or you can build it in some ubuntu 18.04 system and copy shared libraries. But here you may have some next troubles as different path to openssl .so files on heroku system and your. And you should deal with it. So it harder and sounds ugly : )
2. as I said before you can deploy your app as docker container (best choice imho) - https://devcenter.heroku.com/articles/container-registry-and-runtime . you can use heroku's base image - https://devcenter.heroku.com/articles/heroku-18-stack and build own for you app appending our commands from our documentation - https://docs.cossacklabs.com/pages/documentation-themis/#installing-themis-core
Here is our own dockerfile for another our product Acra where we build it with docker and install themis as a dependency with oneline-script which install themis - https://github.com/cossacklabs/acra/blob/master/docker/acra-build.dockerfile#L32 (lifehack for you)
Docker container better because you can setup some automated ci/cd and don't repeat all steps in case 1 if you will need to update themis libraries or heroku will change something in their environment.

because heroku is not free VPS where you can do whatever you want and they want to be safe from malicious commands from unknown users, they allow you to deploy docker containers which they can isolate from main system.

**Comment by vixentael** [comment]
hey @dloughran295 any success with installation on Heroku?

**Comment by vixentael** [comment]
didn't get any response from @dloughran295 :(
