### ISSUE TITLE
Python Themis Docs

### ISSUE THREAD

**Issue by YoomamaFTW** [cossacklabs/themis#521]
Hi, I love encryption, but I found the docs to be confusing for Python. Maybe it's just Themis in general, so please correct me if I'm wrong since this is my first time using Themis.
 
Here is the confusing part: [https://github.com/cossacklabs/themis/wiki/Python-Howto#example-1](https://github.com/cossacklabs/themis/wiki/Python-Howto#example-1)
When you're unwrapping the message, you need to use the private key of the second person. So in the docs, there's:
```
try:
    message = smessage.unwrap(encrypted_message)
except ThemisError as e:
    print(e)
```
Maybe have this instead be:
```
try:
    smessage = SMessage(keypair2.export_private_key(), keypair1.export_public_key())
    message = smessage.unwrap(encrypted_message)
except ThemisError as e:
    print(e)
```
That's the only way it works. Am I doing this right? Or is there another way for decrypting. 

Additionally, for SMessage, two arguments are required. In reality, you should only need one for asymmetric encryption, right? Is this a Themis thing or can we make separate functions to do this?

**Comment by YoomamaFTW** [comment]
Not sure if there is any better place to ask this (if so, please guide me :D), but I'm planning on making a full-stack application. Python on the backend and mobile iOS and Android on the front. My rundown with Themis is this: user creates key-pair on phone on signup. Encrypt each pair separately as a "message" with the server's public key, then send the key-pair over TLS/SSL and store in Postgres. I'm having trouble wrapping my head around the encryption part of the message because right now, I print my public key in Python and b'asdfasdfasf' (something like that) spews out. How do I translate that into a proper... string so that I can store it in the apps for it to be used for encrypting later on? Are the keys in Python encoded in UTF-8? I have this:

```
from pythemis.skeygen import GenerateKeyPair, KEY_PAIR_TYPE
keygen1 = GenerateKeyPair(KEY_PAIR_TYPE.RSA)
print(keygen1.export_public_key())
```
```
b'URA2\x00\x00\x01\x10oAU>\xd5\xd0\x17\xe4\xae#\xa2\x0e``\x86P\x16\xeeY\xe5{;\xb9\xee^\x08\x0f\xfa\x08\xad^\xb9]^m\x97\xf1M\x8c5\xa2\x1e\xc2\x8a\xd5!\xcbe\x18.P\x92\xf1q\x11\xbdK\xf6@\x88\x9f(\x02C\x05\xf5jj!\xac|\x9a}\x92k#1/\xa4\xc4,\x02\x1b3\x07>\xa6.\x07W\xbb\x89\xc0V~\x82\x83\xf8V^\x1e\x85\xc9\xc1\x19\xb2\x13\xd2*8\x13L\xb7\xb2\x89Lp\x80\x1e\x92\x14\x08X\xda(\xac\x0e\xec\x10\x14:7o\xdd\x88\xfcVI\xf4:\xbe\xfeO\xda3\xac\xdc\x92\xf2\x9bu\xd3\xa9\xfe\x8e\xa6b.\xf5\x08\x89\x9a#\xe4\xe3~\xc7s;\xb4\xc9\x8f\x02\xcc\xedl\xcd\xcd\xb8\x93_\x9d\x00C\xe0SBA\x06&\xebi\x15N\xf6\xe3\xd2\x01u\xc3\x1f% \xa1\xc0\xf7)\x1d\xf0\xdcf\x16$\x9b\x1b4*\xe1\xe9V\xadf\x15\x00\x8c\xe9"\xc9\x99\x81D\x1d\x03\xb1\xe1\rEV|A$k\xf4~\x88%\x07\xc4Yc\xfb\x06c\xa7=\\\xfawD7\x00\x01\x00\x01'
```
I append to the print statement like this:
print(keygen1.export_public_key().decode('utf-8'))
But it returns UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 9-10: invalid continuation byte
Noticed the ctypes and such, but still not sure how to go about this. Thanks for reading and helping!

**Comment by vixentael** [comment]
@YoomamaFTW, thank you for questions and comments! For us it's a source of positive changes :)

Let me go one by one.

1. SMessage, asymmetric encryption. Alice and Bob, each of them have a keypair. They exchange public keys (they never exchange private keys). To encrypt messages to Bob and decrypt from him, Alice uses her private key and Bob's public key. To decrypt messages from Alice and to encrypt messages to her, Bob uses his private key and Alice's public key. They never send private keys to each other.

Let's see in action (I use python 3.7.0 on macOS, system libThemis is installed from brew, pythemis is installed from pip):

```
$ python3 
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
> import pythemis
>
```

Step 1. Generating keypairs for Alice and Bob. Assume, that Alice and Bob are different users of your system, or client app and server app.

```
> from pythemis.skeygen import GenerateKeyPair, KEY_PAIR_TYPE
> alice = GenerateKeyPair(KEY_PAIR_TYPE.EC)
> alice_priv_k = alice.export_private_key()
> alice_pub_key = alice.export_public_key()
> bob = GenerateKeyPair(KEY_PAIR_TYPE.EC)
> bob_priv_k = bob.export_private_key()
> bob_pub_k = bob.export_public_key()
```

Step 2. Alice sends her public key to Bob, and Bob sends his public key to Alice (in network call, or your backend is responsible for key exchange, or you use PKI). Now each have 3 keys: own keypair and other party public key.

Step 3. Alice encrypts message for Bob and sends it to him:

```
> from pythemis.smessage import SMessage, ssign, sverify
> from pythemis.exception import ThemisError
> 
> 
> smessageAlice = SMessage(alice_priv_k, bob_pub_k)           
> encFromAlice = smessageAlice.wrap(b'hello from Alice')
> print(encFromAlice)
b" '\x04&D\x00\x00\x00\x00\x01\x01@\x0c\x00\x00\x00\x10\x00\x00\x00\x10\x00\x00\x00\x1c\xda\xf0N\xd1\x85\xb8\xa7Q\xa4\xc6\xef9M;+\x07\xdcQ\x9a*\x96\xa6\x1c\x1a\x0b\xe9\x92=%\xfaC^/\xa3\xd6{\x0b\xfa\\I\xc3 \xcd"
```

Step 4. Bob receives the message from Alice and decrypts it:

```
> smessageBob = SMessage(bob_priv_k, alice_pub_key) 
> decryptedFromAlice = smessageBob.unwrap(encFromAlice)
> print(decryptedFromAlice)
b'hello from Alice'
```

Step 5. Bob decides to encrypt message to Alice, and sends it to her:

```
> encFromBob= smessageBob.wrap(b'hello from Bob!')   
> print(encFromBob)
b" '\x04&C\x00\x00\x00\x00\x01\x01@\x0c\x00\x00\x00\x10\x00\x00\x00\x0f\x00\x00\x00\xc7I\x14f0lpf\xdb\x9f\xd5\xbf\x8a\\;5\x9f&a\xdd\r\x00y\xb6E\xf1UPhyq\xb6\x1e\x01!\xbf\x9b\xdc\xae#\r\xdeb"
```

Step 6. Alice gets the message, decrypts it:

```
> decryptedFromBob = smessageAlice.unwrap(encFromBob)
> print(decryptedFromBob)
b'hello from Bob!'
```

That's it!

Using SecureMessage should make it easier to build client-server apps and prevent mistakes with keys to use, that's why it uses two keys in init.

2. How to build client-server apps easier? Try our [online simulator](https://docs.cossacklabs.com/simulator/data-message/), that works as second party ("Bob") and helps you to make sure that you use correct keys.

3. To send keys and encrypted messages to backend it's better to encode them as base64 strings, because nor keys, nor encrypted messages are not `utf8` strings, but a set of bytes.

4. Not knowing what exactly you're trying to encrypt with Themis, I can't make good suggestions on secure architecture, but usually it's a bad idea to send private keys, even encrypted, to a backend. If you are building commercial app and looking for commercial support, we can dive deeper into your app architecture and suggest proper encryption layout and key management procedures.

Please let me know if this helps or if you have more questions.
