### ISSUE TITLE
Secure session vs SRP

### ISSUE THREAD

**Issue by OlexandrStepanov** [cossacklabs/themis#529]
Hello,

Could you, please, explain how your “Secure Session” approach is any better then SRP one?
Is it also robust to MitM as SRP, and does it solve the issue, that registration must happen via trusted transport channel, i.e. interchange of the “verifier” in terms of SRP.

With respect.

**Comment by vixentael** [comment]
Hello Olexandr! Thank you for your question, let me dig into cryptographic design a bit.

Secure Session and SRP are protocols that have totally different goals and designs.

SRP is a key agreement protocol, which allows client to authenticate on server performing zero knowledge password proof and generating shared session key. The main design goal of SRP is one-way authentication. SRP is known for its limitations and has rich history of finding-and-fixing-and-introducing-new vulnerabilities. Check [Matthew Green's blog post](https://blog.cryptographyengineering.com/should-you-use-srp/) on SRP. If your use-case matches SRP security assumptions, you're much better with one of PAKE primitives.


[Secure Session](https://github.com/cossacklabs/themis/wiki/Secure-Session-cryptosystem) is a communication protocol, that has two stages: negotiation stage to perform mutual authentication between client and server and to derive session key; and data exchange stage where each message is encrypted with integrity checks and respecting sequence numbers. The main goal of Secure Session is to protect network communication during long time. Secure Session uses ECDH, in general ECC support provides more efficient implementation with comparable security guarantees than finite field arithmetic used by SRP.

Yes, Secure Session is supposed to have stronger MitM resistance due to more modern cryptography and less things to fail down the line, but comparing "registration" (server records the derivative of a secret first time from client) to "key exchange" (parties exchange their public keys and identify themselves) is a bit of apples vs oranges - these are two different use-cases.


However, let me introduce one more cryptosystem to this comparison: [Secure Comparator](https://github.com/cossacklabs/themis/wiki/Secure-Comparator-cryptosystem). Secure Comparator is a direct alternative to SRP in terms of comparing two secrets with MitM resistance.

Secure Comparator is ZKP-based authentication protocol, which enables two parties to compare secrets without revealing them. Secure Comparator is based on SMP family, and unlike SRP, that has one-way authentication mechanism, Secure Comparator provides mutual authentication. From cryptography perspective, SRP requires explicit salt to protect from replay attack, where Secure Comparator has such protection in the basic design. Also, because of extended required cryptographic primitives (need to do field element multiplication), it is hard to port SRP to ECC domain.


**TLDR:** 
- when protecting session-like communication between two parties, use Secure Session.
- when performing ZKP authentication or comparing if both parties have same 'secret' (password, SSN, tax id) – use Secure Comparator.
- if you already have system that uses SRP and it satisfies your threat model - stick to it, but make sure it's a secure implementation (many even public ones are broken in un-obvious ways) and keep on using it.

**Comment by OlexandrStepanov** [comment]
Hello @vixentael ,

Thank you very much for such comprehensive answer to my question, much appreciated.

I have looked at Secure Comparator [paper](https://cossacklabs.com/files/secure-comparator-paper-rev12.pdf) and got its main idea. However it still requires first time exchange of secret on user registration using trusted channel, is not it? And if this secret will be caught by malefactor, MitM resistance of Secure Comparator goes away, the same as in SRP case.

>Yes, Secure Session is supposed to have stronger MitM resistance due to more modern cryptography and less things to fail down the line

As far as I understand, Secure Session is based on ECDH, which is [still](https://crypto.stackexchange.com/a/35605) affected by active MitM attack, as well as classic DH key exchange algorithm. What particularly did you mean by stronger MitM resistance?

With regards.

**Comment by gene-eu** [comment]
> However it still requires first time exchange of secret on user registration using trusted channel, is not it? 
>As far as I understand, Secure Session is based on ECDH, which is still affected by active MitM attack, as well as classic DH key exchange algorithm. 

Secret / key distribution trust is outside of the typical threat model for ECDH as well as SC (and as well as SRP, in fact!). Both ECDH and SC imply that you have exchanged credentials safely - first is a protocol for deriving shared secret from two keypairs via interactive protocol, second is verifying that there is a shared secret between two parties. 

Neither of them is designed to distribute the initial material securely, so in neither case there is a "active MiTM attack" against them. There is an active MiTM attack against systems which don't do key management properly and use these primitives. 

Typical solution for ECDH is having a PKI (trusted third party verifying key validity) or trusted channel to exchange keys. Typical solution for SC would be establishing trust via other matters. There are untypical solutions fine-tailored to use-cases. 

To avoid lengthy theoretical discussions and wordy copypasta from cryptography textbooks, if you're having something beyond academic interest, it would make sense to discuss this in some practical use-case you're trying to solve. 

>What particularly did you mean by stronger MitM resistance?

If we narrow the context in a way I did above, Matthew Greene's post should give you sufficient detail. 

Happy to discuss the problem in context of practical use-case you're trying to figure it out for.

**Comment by OlexandrStepanov** [comment]
Hello @gene-eu,

If talking about practical case, I'm exploring approaches for SSL pinning to defense from MitM attack, but at the same time looking at the protocols, which may resist in MitM in case if SSL pinning will fail.
I've heard, that SRP is MitM resistant. But it has this problem of the first exchange of verifier from client to server, which must happen using trusted channel.
I was thinking protocols you have developed don't have this limitation. But it seems, that it's principal limitation of all protocols from ZKP class, which may be worked around by using another channel, like Email, SMS, physical letter, how crazy it wouldn't sound.

Could you explain, please, what is the sense of using Secure Session over TLS 1.3? They seem solving the same problem to me. Or is it about adding another layer of security?

With regards.

**Comment by gene-eu** [comment]
Well, there is a general problem for cryptographic protocols: they are built for one small function rather than "make stuff secure magically". SS does transport, SC / SRP - secret comparison. 

They are MiTM resistant within their scope of responsibility. 

>but at the same time looking at the protocols, which may resist in MitM in case if SSL pinning will fail.

SC could help there, but it heavily depends on trust model. Do you protect against active MiTM that only has access to transport or that same active MiTM is expected to have privileged access to one of sides of exchange?

>I've heard, that SRP is MitM resistant. But it has this problem 

It's not a "problem" (neither it is a "weakness") - it's just another design challenge that is solved otherwise elsewhere.

> I was thinking protocols you have developed don't have this limitation. 

As I said above, within each of the use-cases there is an established way to solve the initial trust or verification problem - PKI, "record then trust what you've recorded", side trusted channel, etc.,- which are chosen based on your actual system design. 

>Could you explain, please, what is the sense of using Secure Session over TLS 1.3? 

SS is efficient where you want: 

* something lighter than TLS
* something that is easy to fold socket into within an application
* something that can be manipulated and bent in various ways
* something that enforces mutual authentication and forward secrecy inside the protocol, regardless of misconfiguration. 

Cryptographically they provide pretty much the same level of guarantees.

In most cases, TLS 1.3 would suffice. SS is not for the "most cases", though.

**Comment by vixentael** [comment]
I think we’ve solved the initial issue, and currently this thread looks like `cryptographic engineering 101` course, which is very outside the purpose of Themis GH issues.

@OlexandrStepanov thank you for your questions, I hope that main difference between different crypto protocol families is more-or-less clear now. If you need security engineering advice for your specific case –  we run [consulting program](https://cossacklabs.com/dgap/) for these purposes.

Also, we tend to describe security design & architecture in details in [our blog](https://cossacklabs.com/blog).
