### ISSUE TITLE
iOS decryption using TSCellTokenEncryptedData is not working

### ISSUE THREAD

**Issue by parthh** [cossacklabs/themis#647]
**Describe the bug**
We have integrated themis on our backend and mobile app. so encrypted data using the themis secure cell token protected method is coming from the API to mobile. when ios App try to decrypt that  using the same masterkey that backend use and with give ciphertext and token library throwing the error

**To Reproduce**
1. Master key: b0gyNlM4LTFKRDI5anFIRGJ4SmQyLGE7PYA8KLQbT5K=

```swift
let hash = "abDoZIU="
let token = "AAEBQAwAAAAQAAAABQAAAJ52NkaXhYJFmmE5DB8muA6itiN2NecN1kfb2RA="

let cipherText =  Data(base64Encoded: hash, options: .ignoreUnknownCharacters)!
let cipherToken =  Data(base64Encoded: token, options: .ignoreUnknownCharacters)!
var encryptedMessage: TSCellTokenEncryptedData = TSCellTokenEncryptedData()
encryptedMessage.cipherText = NSMutableData(data:cipherText)
encryptedMessage.token = NSMutableData(data:cipherToken)

do {
    let decryptedMessage: Data = try cellToken.unwrapData(encryptedMessage, context: nil)
    let resultString: String = String(data: decryptedMessage, encoding: .utf8)!
    print("decryptedMessage = \(resultString)")
} catch let error as NSError {
    print(error.localizedDescription)
    print("Error occurred while decrypting \(error)", #function)
    return
}
```

3. See the following error:
```
ThemisDemo/Pods/themis/src/themis/sym_enc_message.c:345 - error: themis_auth_sym_plain_decrypt(hdr->alg, derived_key, derived_key_length, iv, hdr->iv_length, in_context, in_context_length, encrypted_message, hdr->message_length, message, message_length, auth_tag, hdr->auth_tag_length)

Error occurred while decrypting Error Domain=com.CossackLabs.Themis.ErrorDomain Code=11 "Secure Cell (Token Protect) decryption failed" UserInfo={NSLocalizedDescription=Secure Cell (Token Protect) decryption failed} decryptData()

```

**Expected behavior**
It should be decrypted if we send base 64 decoded data to TSCellTokenEncryptedData as we are able to decrpyt the same data on Android, Node.js and https://docs.cossacklabs.com/simulator/data-cell/

**Environment (please complete the following information):**
- OS: [latest ios]
- Hardware: [64-bit, or iPhone 11 Max SIMULATOR]
- Themis version:  0.12.2
- Installation way:
   - cocoapod

**Additional context**
Add any other relevant context for the problem here. Share an example project, if you can.

**Comment by ilammy** [comment]
Hi @parthh!

Thanks for reporting an issue. The issue exists, but I believe it’s not with SwiftThemis but with our documentation for Themis Interactive Simulator.

### Why the code does not work

In Swift code you have to decode the key into `Data`:

```swift
let masterKey = Data(base64Encoded: "b0gyNlM4LTFKRDI5anFIRGJ4SmQyLGE7PYA8KLQbT5K=",
                     options: .ignoreUnknownCharacters)!
let cellToken = TSCellToken(key: masterKey)!
```

because `TSCellToken` accepts only `Data`.

However, the interactive simulator does not decode the key as base64. Instead it interprets it as UTF-8 text. When you input the key like this into the simulator:

<img width="889" alt="Simulator screenshot" src="https://user-images.githubusercontent.com/1256587/83452903-3586d300-a462-11ea-91b7-0bd6d9fa1a91.png">

The _actual_ key that is used for encryption is not

```swift
let masterKey = Data(base64Encoded: "b0gyNlM4LTFKRDI5anFIRGJ4SmQyLGE7PYA8KLQbT5K=",
                     options: .ignoreUnknownCharacters)!
```

but rather

```swift
let masterKey = "b0gyNlM4LTFKRDI5anFIRGJ4SmQyLGE7PYA8KLQbT5K=".data(using: .utf8)!
```

Effectively, the data was encrypted with a key different from the one used for decryption, which causes the decryption to fail.

### What code works successfully

If you use the same key as the simulator, the incorrectly decoded key, then the data can be decrypted successfully:

```swift
let masterKey = "b0gyNlM4LTFKRDI5anFIRGJ4SmQyLGE7PYA8KLQbT5K="
let hash = "abDoZIU="
let token = "AAEBQAwAAAAQAAAABQAAAJ52NkaXhYJFmmE5DB8muA6itiN2NecN1kfb2RA="

let cipherText = Data(base64Encoded: hash, options: .ignoreUnknownCharacters)!
let cipherToken = Data(base64Encoded: token, options: .ignoreUnknownCharacters)!
let encryptedMessage = TSCellTokenEncryptedData()
encryptedMessage.cipherText = NSMutableData(data: cipherText)
encryptedMessage.token = NSMutableData(data: cipherToken)

let correctKey = Data(base64Encoded: masterKey, options: .ignoreUnknownCharacters)!
let cellTokenDoesNotWork = TSCellToken(key: correctKey)!
let decryptedMessageFail = try? cellTokenDoesNotWork.unwrapData(encryptedMessage, context: nil)

let nilMessage = "<nil>".data(using: .utf8)!
print("decryptedMessage = \(String(data: decryptedMessageFail ?? nilMessage, encoding: .utf8)!)")
// prints "decryptedMessage = <nil>"

let simulatorKey = masterKey.data(using: .utf8)!
let cellTokenThisWorks = TSCellToken(key: simulatorKey)!
let decryptedMessageOk = try? cellTokenThisWorks.unwrapData(encryptedMessage, context: nil)

print("decryptedMessage = \(String(data: decryptedMessageOk ?? nilMessage, encoding: .utf8)!)")
// prints "decryptedMessage = Hello"
```

### What are the next steps

You cannot use base64-encoded encryption keys with the interactive simulator at the moment. The key used with the interactive simulator must be encoded in UTF-8 when testing the output against the application code.

Could you please verify that using UTF-8 works for you?

**Comment by parthh** [comment]
@ilammy you are good, it worked now
