### ISSUE TITLE
Unable to install JS Themis on Windows

### ISSUE THREAD

**Issue by papb** [cossacklabs/themis#670]
**Describe the bug**

Unable to install JS Themis on Windows

**To Reproduce**

1. Run `npm i jsthemis` on an empty folder

2. See the following error:

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cpp
  errors.cpp
  secure_message.cpp
  secure_keygen.cpp
  secure_session.cpp
  secure_cell_seal.cpp
  secure_cell_context_imprint.cpp
  secure_cell_token_protect.cpp
c:\users\pedro\node_modules\jsthemis\errors.hpp(22): fatal error C1083: Cannot open include file: 'themis/themis.h': No such file or directory (compiling source file ..\addon.cpp) [C:\Users\pedro\node_modules\jsthemis\buil
d\jsthemis.vcxproj]
  secure_comparator.cpp
c:\users\pedro\node_modules\jsthemis\secure_session.hpp(24): fatal error C1083: Cannot open include file: 'themis/themis.h': No such file or directory (compiling source file ..\secure_session.cpp) [C:\Users\pedro\node_modu
les\jsthemis\build\jsthemis.vcxproj]
..\secure_message.cpp(21): fatal error C1083: Cannot open include file: 'themis/themis.h': No such file or directory [C:\Users\pedro\node_modules\jsthemis\build\jsthemis.vcxproj]
c:\users\pedro\node_modules\jsthemis\secure_keygen.hpp(24): fatal error C1083: Cannot open include file: 'themis/themis.h': No such file or directory (compiling source file ..\secure_keygen.cpp) [C:\Users\pedro\node_module
s\jsthemis\build\jsthemis.vcxproj]
  win_delay_load_hook.cc
..\secure_cell_context_imprint.cpp(23): fatal error C1083: Cannot open include file: 'soter/soter.h': No such file or directory [C:\Users\pedro\node_modules\jsthemis\build\jsthemis.vcxproj]
..\secure_cell_seal.cpp(23): fatal error C1083: Cannot open include file: 'soter/soter.h': No such file or directory [C:\Users\pedro\node_modules\jsthemis\build\jsthemis.vcxproj]
c:\users\pedro\node_modules\jsthemis\errors.hpp(22): fatal error C1083: Cannot open include file: 'themis/themis.h': No such file or directory (compiling source file ..\errors.cpp) [C:\Users\pedro\node_modules\jsthemis\bui
ld\jsthemis.vcxproj]
..\secure_cell_token_protect.cpp(23): fatal error C1083: Cannot open include file: 'soter/soter.h': No such file or directory [C:\Users\pedro\node_modules\jsthemis\build\jsthemis.vcxproj]
c:\users\pedro\node_modules\jsthemis\secure_comparator.hpp(24): fatal error C1083: Cannot open include file: 'themis/themis.h': No such file or directory (compiling source file ..\secure_comparator.cpp) [C:\Users\pedro\nod
e_modules\jsthemis\build\jsthemis.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\pedro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pedro\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pedro\node_modules\jsthemis
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Expected behavior**

Should install

**Environment (please complete the following information):**
- OS: Windows 7
- Hardware: 64-bit
- Themis version: 0.13.0 (latest at the time of this writing)
- Installation way:
   - [x] via package manager
   - [ ] built from source

**Comment by ilammy** [comment]
Hi @papb! Thanks for reporting this issue.

JsThemis requires Themis Core library to be installed in the system. This is an additional native library which **npm** cannot install. It seems that it is not installed, its headers are missing, and the builds fails because of that.

The bad news is that Windows support is still experimental. You will have to build Themis Core from sources for now. [Here are instructions](https://docs.cossacklabs.com/themis/installation/installation-from-packages/#windows) on how to build Themis Core for Windows using MSYS2. That should produce an installer which installs Themis Core into a location known by JsThemis.

At some point we want to provide proper binary builds of Themis Core for Windows. However, right now you will have to build it yourself 😞 That is, if you wish to use JsThemis specifically. (There are valid reasons for that. Performance is one of them.)

However, there is also **WasmThemis** which supports JavaScript apps and Node.js as well. It should work on Windows as is, without Themis Core. The API is mostly similar to JsThemis (but there are slight differences). You can install it with

```
npm install wasm-themis
```

[Here are the docs on WasmThemis](https://docs.cossacklabs.com/themis/languages/wasm/) for further reading.

Maybe it will be a better fit for Windows development.

**Comment by papb** [comment]
Thank you for the fast and detailed response, @ilammy!! I just tried `wasm-themis` and it works perfectly!! Thank you very much.

Question: is there any situation/reason for someone to prefer `jsthemis` over `wasm-themis`? Is there anything that `jsthemis` can do that `wasm-themis` can't?

**Comment by ilammy** [comment]
JsThemis is intended for *server-side deployment* with Node.js (and Node.js only). It is designed to use the shared Themis Core library, with an intention of making it possible to update Themis Core independently of JsThemis or applications. For example, if a security vulnerability is discovered and fixed in Themis Core then with JsThemis you only need to update Themis Core in the system. You do not have to update JsThemis, rebuild applications, etc.

WasmThemis is intended for *Web deployment* and it uses WebAssembly (so it works in browsers, as well as with Node.js, and it's easier to use with Electron). It is designed on the premise that the user gets the entire application with all dependencies. In order to update WasmThemis the application should be rebuilt and redeployed.

The shared library aspect of JsThemis becomes less and less relevant as more applications turn to sandboxing. On Windows shared libraries were never popular in the first place. macOS is mostly sandboxed nowadays too. On Linux server-side software is often deployed in containers, and desktop software often uses sandboxes like Snap, Flatpak, Electron bundles, etc.

*Feature-wise,* JsThemis and WasmThemis are identical. All Themis features are available in both of them. The API is different in some cases, but anything you can with WasmThemis is possible with JsThemis as well (or any other language wrapper).

JsThemis uses native binary code, executing with the maximum possible performance. That means that it has to be compiled for a specific machine and a specific version of Node.js that will be running the code.

WasmThemis uses portable WebAssembly which is usually JIT-compiled before execution, but the compiler is not *that* efficient right now. I don't remember the exact benchmark numbers, but as a result WasmThemis is usually 2–3 times slower than JsThemis.

Basically, use WasmThemis if you

- write a web app for browsers
- want a simpler deployment (not have to mess with native libraries)
- need to deploy portable code

Use JsThemis if you

- need more performance than WasmThemis can offer now
- want to be on the safe side with security updates for servers
- target primarily servers or desktops

**Comment by papb** [comment]
Awesome, thank you very much!!
