### ISSUE TITLE
Is there a limit to the size of the data to be encrypted/decrypted with Secure Cell, Seal Mode?

### ISSUE THREAD

**Issue by papb** [cossacklabs/themis#690]
I have read the following sections of the docs but I couldn't find information on whether or not there is a size limit to the [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) to be passed for a Secure Cell to encrypt/decrypt.

* https://docs.cossacklabs.com/themis/languages/wasm/features/#seal-mode
* https://docs.cossacklabs.com/themis/crypto-theory/cryptosystems/secure-cell/

Is there a limit? What is it?

Also, is there a limit for the size of the password? What is it?

Thank you very much!

**Comment by ilammy** [comment]
The data format of Secure Cell allows up to 4 GB of data in a single cell. Other cryptosystems typically have the same theoretical restrictions due to their data formats and protocols using unsigned 32-bit integers for sizes.

There is no theoretical upper limit on the size of the key or the password. (There is a lower one: neither the data, the key, nor the password can be empty.)

Usually this doesn't come into play as practical limits are lower. This is why it's not documented explicitly.

As for WasmThemis, WebAssembly currently has 32-bit addresses so it could – theoretically – squeeze up to 4 GB in a single UintArray. However, you have to take into account that you need an equal amount of storage for the result to be returned, that there is other stuff in Wasm memory besides Themis, that the browsers puts limits on how much a single module can allocate, etc. The practical limit is lower. Effectively, you are unlikely to reach the limit of Themis before something else breaks.

**Comment by papb** [comment]
Awesome, thank you very much for the fast and detailed response! :smiley:

**Comment by vixentael** [comment]
Thank you @papb! I believe the question was answered, and we added improving docs task on our board.

I'm closing the issues, feel free to open new one if you have questions!
