### ISSUE TITLE
Secure session and offline chat application

### ISSUE THREAD

**Issue by FunnyDevs** [cossacklabs/themis#694]
I have read the secure session documentation and this article about Themis chat application

https://medium.com/cryptographic-engineering/building-encrypted-chat-service-with-themis-and-mobile-websocket-example-a48407bd9afe

and i understand that it is used for syncronous communication.

Can i use secure session for offline/asyncronous messaging like the signal protocol does? 

Thanks

**Comment by vixentael** [comment]
Hi @FunnyDevs!

You're right, SecureSession's main purpose is to protect sync communication channel, i.e real time communication between devices.

For async communication you can use [SecureMessage](https://docs.cossacklabs.com/themis/crypto-theory/cryptosystems/secure-message/) to encrypt messages. It uses private key of one party and public key of another party to derive shared secret and encrypt/decrypt message. When you encrypt the data with SecureMessage, you can use any transport protocol to deliver it to the other party.

However, if you final goal is to build Signal-like chat application, then consider protocols tailored specifically for chatting, like signal protocol.

**Comment by ilammy** [comment]
Secure Session protocol itself *can* be used for asynchronous messaging, but it's poorly supported.

That is, it is possible to prepare some messages in advance and send them later, or transport them by other channel, without immediate connectivity with the peer. However, in order to fully support this use case, it is necessary to have an ability to restore an established session after a power cycle. Secure Session has this option but it's supported only for Java/Kotlin (and we consider deprecating it).

Furthermore, Secure Session is still sequence-oriented protocol, so you have to keep hold to offline messages, remember the sequence in which they were generated, and deliver them in this sequence later. Secure Session by itself does not help with that in any way. It's not much of a problem in synchronous use cases, but it can be for asynchronous messages since Secure Session was not designed with this use case in mind.

As suggested by @vixentael, Secure Message in encryption mode may be a better fit for asynchronous communication. When used with EC keys, its security should be comparable to Secure Session (e.g., with forward secrecy).

**Comment by FunnyDevs** [comment]
Thank you all for the responses and clarification and i think i'll use Secure Message.
The limit of Secure Message is that i should change frequently peers keypair to "simulate" a sort of perfect forward secrecy: if Alice  and Bob use SecureMessage to communicate but Bob private key is compromised, the attacker can read all messages, or am I wrong?

**Comment by ilammy** [comment]
Yes, you are right. If Alice encrypts a message for Bob with Secure Message, then if Bob's private key is compromised it becomes possible to read messages from Alice (or anybody else sending to Bob anytime). If Alice's private key is compromised, the messages are still be secure as Bob's private key is required to obtain the shared secret used to encrypt the message.

Secure Session offers more guarantees as keys of both parties (or Secure Session state) need to be compromised in order to read intercepted messages.
