### ISSUE TITLE
Transparent hood

### ISSUE THREAD

**Issue by cossacklabs** [cossacklabs/themis#8]
Object returning a string with current cryptographic algorithm choices for current object.

**Comment by cossacklabs** [comment]
@mnaza, can't we just move all defines related to cipher choice to one .h file and reference that .h file everywhere in docs? Is there anything but clang madness which limits us from it?

**Comment by cossacklabs** [comment]
Still EC-part is left. Can we summon @ignat1 and @mnaza to talk about this issue a bit?

**Comment by mnaza** [comment]
Algorithms can be selected by adding make param: AUTH_SYM_ALG, SYM_ALG and RSA_KEY_LENGTH. Now supported only one ECurve and param for curve selection not needed.

**Comment by gene-eu** [comment]
I've written the explanation:
@secumod @mnaza let me know if I wrote everything correctly
@vixentael @mobrio let me know if it's understandable

https://github.com/cossacklabs/themis/wiki/2.1-Building-and-installing

**Comment by mnaza** [comment]
Yes, everything is correct.

**Comment by secumod** [comment]
+1

**Comment by vixentael** [comment]
@gene-eu yep, understandable.

But i don't really like these `'in most cases'` words. It sounds as we're not sure that Themis is a working piece of software. 

But we are. 

I propose to get rid of these uncertain phrases: they are useless for end-users, hinting on possible problems without providing solutions.

If there is a known set of cases what could possible go wrong during installation, i suggest to create new paragraph `troubleshooting`. It's common practice.

**Comment by gene-eu** [comment]
agree, will fix

**Comment by mobrio** [comment]
I realise the doc is "Building and Installing" but for completeness perhaps mention
```make uninstall```

In testing this I noticed that uninstall can fail because of it's dependencies:
```uninstall: phpthemis_uninstall rubythemis_uninstall pythonthemis_uninstall```

If you have **not** installed phpthemis then no makefile will have been generated in src/wrappers/themis/php so the attempt to uninstall phpthemis with ```make distclean``` fails and causes the whole uninstall process to stop. I don't know if this would also apply similarly for python or ruby.

One possible "Troubleshooting" case is the need to:
```sudo make install```

A more esoteric "Troubleshooting" case is OS X 10.11 SIP (aka Rootless). The makefile itself now does all the right things and all you need to do is:
```make phpthemis_install PREFIX=/usr/local```

However, the ```phpize``` generated ./configure uses ```php-config --extension-dir''' to determine the final destination for phpthemis.so. The default /usr/bin/php-config will return something like /usr/lib/php/extensions/no-debug-non-zts-20121212 ... which is non-writable with SIP.

A solution to this (there may be others) is to:
1. Create a directory such as /usr/local/lib/php/extensions/sipfix
2. Copy /usr/bin/php-config to /usr/local/bin/php-config and amend it to reference the new directory
3. ```make phpinstall PREFIX=/usr/local```will now install /usr/local/lib/php/extensions/sipfix/phpthemis.so
4. In php.ini set extension= /usr/local/lib/php/extensions/sipfix/phpthemis.so (i.e. use the full path)

**Comment by vixentael** [comment]
@mobrio awesome findings! :+1:

**Comment by gene-eu** [comment]
done

**Comment by gene-eu** [comment]
@mobrio, this is slightly different issue, I'm moving it to separate ticket.
