### ISSUE TITLE
RubyThemis

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/themis#87]
We need to study current state of Ruby and understand what, apart from EventMachine, which is deprected, to use to build examples for smessage / ssession.

**Comment by gene-eu** [comment]
Still no progress. If we receive any valuable feedback, we'll get it back to roadmap.

**Comment by RST-J** [comment]
What do you mean by "current state of Ruby"?
If you are looking for a framework within which you could show demo code to illustrate how to use themis I'd suggest Rails (which you already know I guess, which is why I'm wondering what precisely you are looking for). By the release of Rails 5 it now supports websockets ([ActionCable](http://edgeguides.rubyonrails.org/action_cable_overview.html)) which could be interesting for you.
I'm developing with Ruby on Rails for a living and stumbled upon your library and this issue because I'm currently investigating what tools are available to build a secure communication system for a web platform where secure means that the platform (we) cannot look into the exchanged data. Although for the basic system I need everything but serverside encryption utilities I'll investigate themis further for whether it helps doing the server side parts of public key management.

If I can help with anything, let me know. But as is I have to say, I probably don't really get the question.

**Comment by gene-eu** [comment]
Current state means which event models / event handling frameworks are currently popular/useful inside Ruby community, apart from things present in Rails.

The reason for not doing Rails support is that we don't have anyone knowing Rails architecture well enough (all current Ruby code is written by seasoned C/C++ folk in their free time, with one eye on Ruby syntax), so we've decided to wait until someone actually needs this feature.

If you'd like to help with Rails wrappers which will be useful for the community, we'd be very happy to help you achieve that in whatever way we can.

**Comment by gene-eu** [comment]
Thanks to @shadinua, we can close this
