### ISSUE TITLE
File Encryption WASM Themis Memory Error abortOnCannotGrowMemory_emscripten_resize_heap 

### ISSUE THREAD

**Issue by djaffer** [cossacklabs/themis#928]
I am seeing this error when trying to encrypt a file of size ~20 mb. Tried to find example but couldn't find any. 

![image](https://user-images.githubusercontent.com/5740725/180587308-ca741dcc-3255-4759-adcc-1331888d7b7c.png)

**Comment by djaffer** [comment]
This is a critical breakage for us and has to be fixed ASAP.

**Comment by vixentael** [comment]
Thank you @djaffer, we will take a look.

Meanwhile, please fill in the template so we can locate the issue easier:

---

**To Reproduce**
Steps to reproduce the behavior:
1. Use '...'
2. Run '...'
3. See the following error:
```
error
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**
- OS: [OS name and version, e.g. iOS 13]
- Hardware: [32-bit/64-bit, or mobile device name and version]
- Themis version: [e.g. 0.12.0]
- Installation way:
   - [ ] via package manager
   - [ ] built from source

**Additional context**
Add any other relevant context for the problem here. Share an example project, if you can.

**Comment by Lagovas** [comment]
does `make LDFLAGS=-s ALLOW_MEMORY_GROWTH=1` help you? Or only if add this directly in the [src/wrappers/themis/wasm/wasmthemis.mk](https://github.com/cossacklabs/themis/pull/929/files#diff-b4a8011f9b3f35968c229b1d05a7cc47e81f6054bee5f269a1082749d93125c9) file?

**Comment by djaffer** [comment]
I am not sure. I want to test it once you add it.

**Comment by Lagovas** [comment]
Most flags can be extended by explicitly specifying for `make` command and don't need to be hardcoded in the makefiles. Will be great if you try it like that. It will be much faster if you depend on Themis releases (not source code updates).

**Comment by djaffer** [comment]
It is a UI package, so I am not sure if it is the best course for us to compile. It is a genuine bug. Please resolve it whenever you can and use whatever way you think is best to fix the issue. For UI package the expectation should not be to compile for a basic feature to work.

**Comment by vixentael** [comment]
@djaffer

1. please fill in the questionary so we know which Themis version you use, and how to reproduce the case.
https://github.com/cossacklabs/themis/issues/928#issuecomment-1193355214

2. What is the smallest file you can encrypt without issues?

3. Please show the encryption code you use.

4. Can you try using SecureCellContextImprint instead of SecureCellSeal to see if the issue persists?
https://docs.cossacklabs.com/themis/languages/wasm/features/#context-imprint-mode

5. if you can't test this flag yourself to make sure it really helps as @Lagovas suggested, you will need to wait until we can reproduce the case, test different fixes and release a fixed version. Instead of blindly adding the flag, we'd like to understand the root cause and make a conscious decision.

**Comment by djaffer** [comment]
@vixentael the fix was just a suggestion. I added the version details about when you first asked along with the code being used to encrypt how I am encrypting in the PR. Sure take your time and check validity. If you have themis on web playground I can try and I tried to add details in PR I added details. do not think it is a lot for your dev to just add an input file and test. 

I am closing this issue as I do not have more time to keep up with this. If you see it worthwhile you can fix it.

**Comment by vixentael** [comment]
now i see the updated PR. Thank you @djaffer, we will take a look

**Comment by djaffer** [comment]
FYI same error with SecureCellContextImprint.

**Comment by ilammy** [comment]
This might also be related to https://github.com/cossacklabs/themis/issues/798

**Comment by vixentael** [comment]
i guess it's fixed in the latest release 0.14.7
https://github.com/cossacklabs/themis/releases/tag/0.14.7

@djaffer please take a look

**Comment by djaffer** [comment]
looks like the file size of libthemis.wasm has increased react build throwing error.

**Comment by djaffer** [comment]
The issue only happens in 0.14.7. The node module is 22 mb for this. The node_modules package for wasm has dist and dist-es6. 

![image](https://user-images.githubusercontent.com/5740725/185797914-1ff32852-2bfb-41e7-8163-3cc0c89cdc53.png)

**Comment by vixentael** [comment]
hmm interesting side effects, @rad remember, we previously compiler Themis with O3 optimization flag?

**Comment by vixentael** [comment]
thank you for a feedback @djaffer!

we have released 0.14.8, that should be both: small & support large files. we have deprecated 0.14.7 as an unfortunate release.
https://github.com/cossacklabs/themis/releases/tag/0.14.8  

could you please take a look?

**Comment by djaffer** [comment]
It is working! Thank you! Size is now 10 MB. One more optimization you guys can do is to have a single copy libthemis.wasm rather than having it in each dist, dist6, and src directories. Removing the 2 extra copies could save 4 MB.

**Comment by djaffer** [comment]
It is working! Thank you! Size is now 10 MB. One more optimization you guys can do is to have a single copy libthemis.wasm rather than having it in each dist, dist6, and src directories. Removing the 2 extra copies could save 4 MB.

**Comment by vixentael** [comment]
thank you, @djaffer!

> One more optimization you guys can do is to have a single copy libthemis.wasm rather than having it in each dist, dist6, and src directories. Removing the 2 extra copies could save 4 MB.

@radetsky that's a good one ^
