### ISSUE TITLE
Larger Custom RSA key sizes (2048, 4096) 

### ISSUE THREAD

**Issue by yen936** [cossacklabs/themis#982]
Is it possible to specify the key size in the RSA/EC pairs. for example:

in the swift flavor:
`let keypair = TSKeyGen(algorithm: .RSA, keySize: 4096)!`
`let privateKey: Data = keypair.privateKey as Data`
`let publicKey: Data = keypair.publicKey as Data`

Similar to pythons `cryptography`

`from cryptography.hazmat.primitives.asymmetric import rsa`
    `private_key = rsa.generate_private_key(`
        `public_exponent=65537,`
        `key_size=4096,`
       ` backend=default_backend(),`
   ` )`
`

**Describe alternatives you've considered**
I gen RSA key pairs inside a Swfit app, then send to pub_key to the python backend. Then verify future message signatures with the pub_key. I have tried other Swift crypto libs (SwCrypt, CryptoSwift, Security, RSAUtils) without fitting the use case. The closest was SwCrypt. but the PSS padding had an internal error. 

Thank you so much!

**Comment by Lagovas** [comment]
Hi. Main our approach is to provide ready to use and secure enough crypto library that hides all complexity of the cryptography from its users. That is why themis doesn't provide API to configure runtime options for crypto algorithms and choose crypto primitives. But on other hand it were designed to be extendable and configurable by experienced in cryptography clients for their needs. That is why you can compile themis with other default parameters for you purposes. All such parameters are hidden by compilation definitions which may be overridden in the compilation stage. https://github.com/cossacklabs/themis/blob/master/src/themis/secure_keygen.c#L33 - here is how defined key size for key generation API. So, you can compile themis from the sources by `make THEMIS_RSA_KEY_LENGTH=4096 && sudo make install` and all key generation functions will generate RSA keys with 4096 size. With EC keys the situation a bit harder because it doesn't allow to override default curve and key size. Now the default is prime256v1

**Comment by vixentael** [comment]
@yen936 would it help if you will switch to Themis completely?

Using pyThemis on backend:
https://docs.cossacklabs.com/themis/languages/python/installation/

and Swift in iOS app:
https://docs.cossacklabs.com/themis/languages/swift/installation/

Themis language wrappers are compatible with each other, thus you will have same cryptography on backend and mobile. No need to change key length.

**Comment by yen936** [comment]
> https://github.com/cossacklabs/themis/blob/master/src/themis/secure_keygen.c#L33

@Lagovas  thank you for your prompt, clear response. Yes I think I will try compiling with the larger key sizes.

**Comment by yen936** [comment]
> @yen936 would it help if you will switch to Themis completely?
> 

@vixentael  thank you for your response. Yes I have switched to pyThemis backend as well along with the Swift implementation. 

> Themis language wrappers are compatible with each other, thus you will have same cryptography on backend and mobile. No need to change key length. And it works better than expected.

I was concerned with[ this paper ](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf)from the National Institute of Standards and Technology in 2023 said "[For RSA Keys used in Digital Signatures] This standard specifies the use of a modulus whose bit length  is an even integer and **greater than
or equal to 2048 bits**."

I was trying to stay ahead of the technological change when they eventually say only > 2048 bits.
